name: Destroy Terraform

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:

jobs:
  destroy_terraform:
    name: Create Terraform
    runs-on: [ubuntu-latest]
    steps:
      - name: Assume Role in ${{ inputs.environment }}
        uses: aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ vars.IR4ASSUMEROLE }}
          aws-region: ap-southeast-1
          role-session-name: githubActionSession

      - uses: actions/checkout

      - uses: hashicorp/setup-terraform

      - name: Terraform format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -destroy -no-color

      - name: Terraform destroy
        run: terraform destroy -auto-approve
